export class BoxerAnimation{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.frames=[];this.queue=[];this.particles=[];this.pose=0;this.poseTime=0;this.clock=0;this.fatigue=0;this.hurt=0;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const sheet=new Image();sheet.onload=()=>this.prepare(sheet);sheet.src=new URL('boxing-sprites.png',import.meta.url).href}
 prepare(sheet){const w=sheet.width/4,h=sheet.height/2;for(let n=0;n<8;n++){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(sheet,n%4*w,Math.floor(n/4)*h,w,h,0,0,w,h);const image=x.getImageData(0,0,w,h),d=image.data,seen=new Uint8Array(w*h),queue=[];const neutral=i=>{const k=i*4,min=Math.min(d[k],d[k+1],d[k+2]),max=Math.max(d[k],d[k+1],d[k+2]);return min>155&&max-min<24};const visit=i=>{if(i<0||i>=w*h||seen[i]||!neutral(i))return;seen[i]=1;queue.push(i)};for(let px=0;px<w;px++){visit(px);visit((h-1)*w+px)}for(let py=0;py<h;py++){visit(py*w);visit(py*w+w-1)}for(let p=0;p<queue.length;p++){const i=queue[p];d[i*4+3]=0;if(i%w)visit(i-1);if(i%w<w-1)visit(i+1);visit(i-w);visit(i+w)}for(let i=0;i<w*h;i++){if(neutral(i))d[i*4+3]=0}x.putImageData(image,0,0);this.frames.push(c)}}
 punch(key,index){this.queue.push({pose:key===0?(index>1?3:1):key===3?2:key===1?4:5,duration:key===2?.24:.18});if(this.queue.length>6)this.queue.shift();this.burst(key===0?-1:1,9)}
 recoil(){this.queue=[];this.pose=6;this.poseTime=.48;this.hurt=.5;this.burst(1,32)}
 burst(dir,count){if(this.reduced)return;for(let i=0;i<count;i++)this.particles.push({x:.52,y:.32,vx:dir*(.08+Math.random()*.28),vy:-.08-Math.random()*.3,life:.35+Math.random()*.45,size:.7+Math.random()*1.5})}
 draw(dt,hp=100,active=false){this.clock+=dt;this.fatigue=(100-hp)/100;this.hurt=Math.max(0,this.hurt-dt);this.poseTime-=dt;if(this.poseTime<=0){const next=this.queue.shift();this.pose=next?.pose??(this.fatigue>.55?7:0);this.poseTime=next?.duration??.05}const canvas=this.canvas,rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=rect.width,h=rect.height;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}const ctx=this.ctx;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!this.frames.length)return;const frame=this.frames[this.pose],bob=this.reduced?0:Math.sin(this.clock*(active?3.8+this.fatigue*3:2))* (3+this.fatigue*3),punch=[1,2,3,4].includes(this.pose),zoom=punch&&!this.reduced?1.045:1,fh=h*.98*zoom,fw=fh*frame.width/frame.height,dx=this.reduced?0:this.pose===1?-12:this.pose===2?12:this.pose===3?-17:Math.sin(this.clock*1.7)*4;ctx.save();ctx.translate(w*.52+dx,h+8+bob+(this.pose===5?24:0));if(!this.reduced)ctx.rotate(this.pose===3?-.065:this.pose===6?.055:0);ctx.globalAlpha=1;ctx.drawImage(frame,-fw/2,-fh,fw,fh);ctx.restore();if(active&&this.fatigue>.35&&Math.random()<dt*12)this.particles.push({x:.48+Math.random()*.09,y:.2,vx:(Math.random()-.5)*.015,vy:.03,life:1.1,size:1.1});for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.4*dt;ctx.globalAlpha=Math.max(0,Math.min(.8,p.life));ctx.fillStyle='#e4f4ff';ctx.beginPath();ctx.ellipse(p.x*w,p.y*h,p.size,p.size*1.6,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;this.particles=this.particles.filter(p=>p.life>0)}
}
export class FightAudio{
 constructor(){this.enabled=false;this.ctx=null;this.lastBreath=0}
 async enable(value){this.enabled=value;if(value){this.ctx??=new(window.AudioContext||window.webkitAudioContext)();await this.ctx.resume();this.bell()}}
 tone(freq,length=.15,volume=.08,type='sine'){if(!this.enabled||!this.ctx)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*.7),c.currentTime+length);g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+length);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+length)}
 noise(length,volume,frequency){if(!this.enabled||!this.ctx)return;const c=this.ctx,buffer=c.createBuffer(1,c.sampleRate*length,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const src=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=frequency;gain.gain.setValueAtTime(volume,c.currentTime);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+length);src.connect(filter).connect(gain).connect(c.destination);src.start()}
 punch(key){this.noise(.11,.16,1900);this.tone(key===1?145:90,.16,.17,'triangle');this.noise(.07,.22,600)}
 hurt(){this.tone(65,.32,.22,'sawtooth');this.noise(.3,.3,850)}
 bell(){this.tone(830,.8,.065);this.tone(1245,.6,.035)}
 breathe(time,hp){if(hp<45&&time-this.lastBreath>2.8){this.lastBreath=time;this.noise(.65,.065,520)}}
}
