export const KEYS=['ArrowLeft','ArrowUp','ArrowDown','ArrowRight'];
export const GLYPHS=['←','↑','↓','→'];
export class Fight{
 constructor(seed=1){this.seed=seed>>>0;this.hp=100;this.rival=100;this.score=0;this.streak=0;this.best=0;this.landed=0;this.level=1;this.inLevel=0;this.remaining=75;this.elapsed=0;this.delay=.8;this.index=0;this.done=false;this.win=false;this.events=[];this.next()}
 random(){this.seed=(Math.imul(1664525,this.seed)+1013904223)>>>0;return this.seed/4294967296}
 next(){const n=Math.min(6,3+Math.floor((this.level-1)/2));this.sequence=Array.from({length:n},()=>Math.floor(this.random()*4));this.index=0;this.duration=Math.max(1.35,4.2-(this.level-1)*.31);this.comboLeft=this.duration;this.events.push({type:'next'})}
 advance(dt){if(this.done)return;let left=dt;while(left>1e-8&&!this.done){let step=Math.min(left,this.remaining,this.delay>0?this.delay:this.comboLeft);if(step<=1e-8)step=Math.min(left,.000001);this.elapsed+=step;this.remaining=Math.max(0,this.remaining-step);left-=step;if(this.delay>0){this.delay=Math.max(0,this.delay-step);if(this.delay<1e-8){this.delay=0;this.next()}}else{this.comboLeft=Math.max(0,this.comboLeft-step);if(this.comboLeft<1e-8)this.miss()}if(this.remaining<=0)this.finish(false,'time')}}
 input(key){if(this.done||this.delay>0)return false;if(key!==this.sequence[this.index]){this.miss();return false}this.events.push({type:'punch',key,index:this.index});this.index++;if(this.index===this.sequence.length){this.streak++;this.best=Math.max(this.best,this.streak);const fast=this.comboLeft/this.duration>.5;const points=(fast?150:100)*this.level*Math.min(5,1+Math.floor(this.streak/3));this.score+=points;this.landed++;this.inLevel++;this.rival=Math.max(0,100-Math.round(this.inLevel/6*100));this.events.push({type:'combo',points,fast});this.delay=.6;if(this.inLevel===6){this.score+=500*this.level;this.events.push({type:'level',level:this.level+1});if(this.level===12){this.finish(true,'champion')}else{this.level++;this.inLevel=0;this.rival=100;this.hp=Math.min(100,this.hp+15);this.remaining=Math.min(120,this.remaining+10);this.delay=1.6}}}return true}
 miss(){const damage=Math.min(35,18+this.level*2);this.hp=Math.max(0,this.hp-damage);this.streak=0;this.delay=.85;this.comboLeft=0;this.events.push({type:'hurt',damage});if(this.hp===0)this.finish(false,'ko')}
 finish(win,reason){if(this.done)return;this.done=true;this.win=win;this.reason=reason;this.events.push({type:'finish',reason})}
 drain(){const e=this.events;this.events=[];return e}
}
export function replay(seed,trace,elapsed){if(!Array.isArray(trace)||trace.length>1500||!Number.isFinite(elapsed)||elapsed<0||elapsed>900000)throw Error('Invalid fight replay');const f=new Fight(seed);let last=0;for(const event of trace){if(!Array.isArray(event)||event.length!==2)throw Error('Invalid input');const [at,key]=event;if(!Number.isFinite(at)||at<last||at>elapsed||!Number.isInteger(key)||key<0||key>3)throw Error('Invalid input');if(at-last<35&&last!==0)throw Error('Inputs are too fast');f.advance((at-last)/1000);f.input(key);f.drain();last=at}f.advance((elapsed-last)/1000);if(!f.done)throw Error('Fight has not finished');return f}
