import {Fight,KEYS,GLYPHS} from './engine.mjs';
import {BoxerAnimation,FightAudio} from './animation.mjs';
const $=id=>document.getElementById(id),dialog=$('game'),animation=new BoxerAnimation($('action-canvas')),audio=new FightAudio();
const API='/api/boxing';let mode='ready',fight=new Fight(),trace=[],match=null,ranked=false,last=0,callTime=0,previousFocus,rankingEntries=[],frameId=0,startRequest=0,lastInput=-Infinity;
function open(){if(dialog.open)return;previousFocus=document.activeElement;dialog.showModal();document.body.style.overflow='hidden';$('start').focus();last=performance.now();cancelAnimationFrame(frameId);frameId=requestAnimationFrame(tick)}
function close(){startRequest++;$('start').disabled=false;$('retry').disabled=false;$('start').textContent='LET’S FIGHT ↗';mode='ready';dialog.close();cancelAnimationFrame(frameId);document.body.style.overflow='';$('intro').hidden=false;$('result').hidden=true;$('paused').hidden=true;$('leaderboard').hidden=true;$('pause').hidden=true;$('fight-call').textContent='';fight=new Fight();update();previousFocus?.focus()}
function update(){$('player-health').style.width=fight.hp+'%';$('rival-health').style.width=fight.rival+'%';$('player-value').textContent=fight.hp+' HP'+(fight.hp<45?' · FATIGUED':'');$('rival-value').textContent=fight.rival+' HP';$('score').textContent=String(fight.score).padStart(5,'0');$('streak').textContent=String(fight.streak).padStart(2,'0');$('landed').textContent=fight.landed+' COMBOS LANDED';$('multiplier').textContent='×'+Math.min(5,1+Math.floor(fight.streak/3))+' MULTIPLIER';$('round').textContent='LEVEL '+String(fight.level).padStart(2,'0');$('fight-time').textContent=String(Math.ceil(fight.remaining)).padStart(2,'0');$('combo-timer').style.width=(fight.comboLeft/fight.duration*100)+'%';$('combo-time').textContent=mode==='ready'?'ARROW KEYS TO STRIKE':fight.delay>0?'RESET YOUR GUARD':fight.comboLeft.toFixed(1)+'s';$('combo-name').textContent=fight.sequence.length+'-HIT COMBO / '+(6-fight.inLevel)+' TO LEVEL UP';$('arrows').replaceChildren(...fight.sequence.map((key,i)=>{const e=document.createElement('span');e.textContent=GLYPHS[key];e.className=i<fight.index?'done':i===fight.index?'active':'';e.setAttribute('aria-label',KEYS[key].replace('Arrow','')+(i<fight.index?' completed':i===fight.index?' next':''));return e}))}
function call(title,sub=''){const t=document.createElement('span');t.textContent=title;$('fight-call').replaceChildren(t);if(sub){const s=document.createElement('small');s.textContent=sub;$('fight-call').append(s)}callTime=1}
async function api(body){const response=await fetch(API,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Leaderboard unavailable');return data}
async function start(){const request=++startRequest;if(!audio.ctx){try{await audio.enable(true);$('sound').textContent='SOUND ON';$('sound').setAttribute('aria-pressed','true');$('sound').setAttribute('aria-label','Mute sound')}catch{}}$('start').disabled=true;$('retry').disabled=true;$('start').textContent='ENTERING THE RING…';match=null;ranked=false;try{match=await api({action:'begin'});ranked=true}catch{}if(request!==startRequest)return;$('start').disabled=false;$('retry').disabled=false;$('start').textContent='LET’S FIGHT ↗';fight=new Fight(match?.seed??crypto.getRandomValues(new Uint32Array(1))[0]);fight.drain();trace=[];lastInput=-Infinity;mode='playing';$('intro').hidden=true;$('result').hidden=true;$('paused').hidden=true;$('leaderboard').hidden=true;$('pause').hidden=false;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause fight');$('rank-form').hidden=true;$('rank-status').textContent='';$('feedback').textContent=ranked?'RANKED RUN · Match the arrows from left to right.':'PRACTICE RUN · Leaderboard is offline.';animation.queue=[];animation.poseTime=0;call('LEVEL ONE',ranked?'YOUR RANK STARTS HERE':'PRACTICE RUN');audio.bell();last=performance.now();update();$('pause').focus()}
function process(){for(const e of fight.drain()){if(e.type==='punch'){animation.punch(e.key,e.index);audio.punch(e.key)}else if(e.type==='hurt'){animation.recoil();audio.hurt();call('GUARD UP!','−'+e.damage+' HEALTH');$('feedback').textContent='Countered. Reset for the next combination.'}else if(e.type==='combo'){call(e.fast?'PERFECT COMBO':'COMBO LANDED','+'+e.points+' POINTS');$('feedback').textContent='Keep the streak alive. Faster combinations are coming.'}else if(e.type==='level'&&e.level<=12){call('LEVEL '+e.level,'+15 HEALTH · +10 SECONDS · FASTER COMBOS');audio.bell()}else if(e.type==='finish'){finish()}}}
function sync(now){if(mode==='playing'){fight.advance(Math.max(0,now-last)/1000);process()}last=now}
function input(key){if(mode!=='playing')return;sync(performance.now());if(mode!=='playing'||fight.delay>0)return;const at=Math.round(fight.elapsed*1000);if(at-lastInput<45)return;lastInput=at;trace.push([at,key]);fight.input(key);process();update()}
function tick(now){const dt=Math.min(.1,Math.max(0,now-last)/1000);sync(now);animation.draw(dt,fight.hp,mode==='playing');if(mode==='playing'){audio.breathe(fight.elapsed,fight.hp);update()}if(callTime>0){callTime-=dt;if(callTime<=0)$('fight-call').textContent=''}if(dialog.open)frameId=requestAnimationFrame(tick)}
function pause(){if(mode==='playing'){sync(performance.now());if(fight.done)return;mode='paused';$('paused').hidden=false;$('pause').textContent='▶';$('pause').setAttribute('aria-label','Resume fight');$('resume').focus()}else if(mode==='paused'){mode='playing';$('paused').hidden=true;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause fight');last=performance.now();$('pause').focus()}}
async function finish(){mode='finished';$('pause').hidden=true;$('result').hidden=false;$('fight-call').textContent='';$('result-label').textContent=fight.win?'ALL TWELVE LEVELS CLEARED':fight.reason==='time'?'THE BELL HAS RUNG':'DOWN FOR THE COUNT';$('result-title').textContent=fight.win?'CHAMPION.':fight.reason==='time'?'TIME’S UP.':'KNOCKED OUT.';$('result-copy').textContent='Level '+fight.level+' · '+fight.landed+' combos landed. '+(fight.win?'The penthouse belongs to you.':'Every round makes you sharper.');$('final-score').textContent=fight.score.toLocaleString();$('final-streak').textContent=fight.best;$('retry').focus();audio.bell();if(!ranked){$('rank-status').textContent='Practice score — reconnect for a ranked run.';return}if(!fight.score){$('rank-status').textContent='Land a combo to earn a place in the rankings.';return}$('rank-status').textContent='Checking your world rank…';const completed=fight;try{const {entries}=await api();if(fight!==completed)return;rankingEntries=entries;const qualifies=entries.length<10||fight.score>entries[9].score;$('rank-status').textContent=qualifies?'TOP TEN MATERIAL. Claim your spot.':'Beat '+entries[9].score.toLocaleString()+' points to enter the top ten.';$('rank-form').hidden=!qualifies}catch{$('rank-status').textContent='Rank check unavailable. Open Top 10 to retry.';$('rank-form').hidden=false}}
function renderRanks(entries){$('rank-list').replaceChildren(...entries.map((entry,i)=>{const li=document.createElement('li');const rank=document.createElement('b');rank.textContent=String(i+1).padStart(2,'0');const name=document.createElement('span');name.textContent=entry.name;const level=document.createElement('small');level.textContent='L'+entry.level;const points=document.createElement('strong');points.textContent=entry.score.toLocaleString();li.append(rank,name,level,points);return li}));$('rank-message').textContent=entries.length?'Shared rankings · Updates may take a moment to appear.':'The ring is waiting for its first ranked fighter.'}
async function loadRanks(){if(mode==='playing')pause();$('leaderboard').hidden=false;$('close-ranks').focus();$('rank-message').textContent='Loading world rankings…';try{const {entries}=await api();rankingEntries=entries;renderRanks(entries)}catch(e){$('rank-message').textContent=e.message==='Failed to fetch'?'Leaderboard is offline. Please try again.':e.message}}
$('rank-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('save-rank');button.disabled=true;$('retry').disabled=true;$('rank-status').textContent='Saving your verified score…';try{const data=await api({action:'submit',id:match?.id,name:$('rank-name').value,trace,elapsed:Math.ceil(fight.elapsed*1000)});$('rank-form').hidden=true;$('rank-status').textContent=data.message;rankingEntries=data.entries;renderRanks(data.entries)}catch(e){$('rank-status').textContent=e.message}finally{button.disabled=false;$('retry').disabled=false}});
$('rankings').onclick=loadRanks;$('refresh-ranks').onclick=loadRanks;$('close-ranks').onclick=()=>{$('leaderboard').hidden=true;(mode==='paused'?$('resume'):$('rankings')).focus()};$('open-game').onclick=open;$('open-alt').onclick=open;$('close').onclick=close;$('return-room').onclick=close;$('start').onclick=start;$('retry').onclick=start;$('pause').onclick=pause;$('resume').onclick=pause;$('sound').onclick=async()=>{try{await audio.enable(!audio.enabled);$('sound').textContent=audio.enabled?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-pressed',String(audio.enabled));$('sound').setAttribute('aria-label',audio.enabled?'Mute sound':'Enable sound')}catch{$('sound').textContent='SOUND UNAVAILABLE'}};
dialog.addEventListener('cancel',e=>{e.preventDefault();if(!$('leaderboard').hidden){$('leaderboard').hidden=true;return}if(!document.body.classList.contains('embed'))close();else if(mode==='playing')pause()});document.addEventListener('keydown',e=>{if(!dialog.open||e.target instanceof HTMLInputElement)return;if(KEYS.includes(e.key)){e.preventDefault();if(!e.repeat&&$('leaderboard').hidden)input(KEYS.indexOf(e.key))}if(e.code==='Space'&&(mode==='playing'||mode==='paused')&&$('leaderboard').hidden){e.preventDefault();if(!e.repeat)pause()}});document.querySelectorAll('[data-arrow]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();input(KEYS.indexOf(b.dataset.arrow))}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause()});
function positionHotspot(){const room=$('room'),img=room.querySelector('img'),w=room.clientWidth,h=room.clientHeight;if(!img.naturalWidth)return;const scale=window.innerWidth<=720?Math.min(w/img.naturalWidth,h/img.naturalHeight):Math.max(w/img.naturalWidth,h/img.naturalHeight);$('open-game').style.left=((w-img.naturalWidth*scale)/2+img.naturalWidth*scale*.785)+'px';$('open-game').style.top=((h-img.naturalHeight*scale)/2+img.naturalHeight*scale*.39)+'px'}window.addEventListener('resize',positionHotspot);$('room').querySelector('img').addEventListener('load',positionHotspot);positionHotspot();if(new URLSearchParams(location.search).get('embed')==='1'){document.body.classList.add('embed');open()}
const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'open_boxing_game',description:'Open the After Hours boxing game start screen.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');open();return{open:dialog.open,state:mode}}})).catch(()=>{})}catch{}}
